// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJJuOTBJKXvEetdbhB_Va8o-OSP3e_cX0',
    appId: '1:896254184017:web:6819ebc51fd13db01bc670',
    messagingSenderId: '896254184017',
    projectId: 'laptrinhdidong-2d0fa',
    authDomain: 'laptrinhdidong-2d0fa.firebaseapp.com',
    storageBucket: 'laptrinhdidong-2d0fa.firebasestorage.app',
    measurementId: 'G-CW97FGLS1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXgQwQRAqL8xWHcVRdv5Pu9-fKPvwplY4',
    appId: '1:896254184017:android:e7293923cd65e4401bc670',
    messagingSenderId: '896254184017',
    projectId: 'laptrinhdidong-2d0fa',
    storageBucket: 'laptrinhdidong-2d0fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP5ef5gFbm7BskG7RhlWYLe4jdhBVsDwo',
    appId: '1:896254184017:ios:83aeb61de16495d71bc670',
    messagingSenderId: '896254184017',
    projectId: 'laptrinhdidong-2d0fa',
    storageBucket: 'laptrinhdidong-2d0fa.firebasestorage.app',
    iosClientId: '896254184017-hcaocvjltq3jiimkjuekfov5nt7csjjl.apps.googleusercontent.com',
    iosBundleId: 'com.example.bai1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP5ef5gFbm7BskG7RhlWYLe4jdhBVsDwo',
    appId: '1:896254184017:ios:83aeb61de16495d71bc670',
    messagingSenderId: '896254184017',
    projectId: 'laptrinhdidong-2d0fa',
    storageBucket: 'laptrinhdidong-2d0fa.firebasestorage.app',
    iosClientId: '896254184017-hcaocvjltq3jiimkjuekfov5nt7csjjl.apps.googleusercontent.com',
    iosBundleId: 'com.example.bai1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJJuOTBJKXvEetdbhB_Va8o-OSP3e_cX0',
    appId: '1:896254184017:web:0cee267375518f1c1bc670',
    messagingSenderId: '896254184017',
    projectId: 'laptrinhdidong-2d0fa',
    authDomain: 'laptrinhdidong-2d0fa.firebaseapp.com',
    storageBucket: 'laptrinhdidong-2d0fa.firebasestorage.app',
    measurementId: 'G-0FMMBTJXFX',
  );

}